# Generated by Django 3.1.8 on 2022-07-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bust', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hips', models.DecimalField(decimal_places=2, max_digits=6)),
                ('neck', models.DecimalField(decimal_places=2, max_digits=6)),
                ('left_thigh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('left_calf', models.DecimalField(decimal_places=2, max_digits=6)),
                ('left_forearm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('left_upper_arm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('right_thigh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('right_calf', models.DecimalField(decimal_places=2, max_digits=6)),
                ('right_forearm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('right_upper_arm', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
