# Generated by Django 3.1.8 on 2022-07-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='neck',
        ),
    ]
