# Generated by Django 3.1.8 on 2022-07-22 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20220719_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 4, 35, 15, 240344, tzinfo=utc)),
        ),
    ]
