# Generated by Django 4.0.6 on 2022-07-28 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 28, 5, 9, 58, 587360, tzinfo=utc)),
        ),
    ]
